import type { ModelDefinition } from '.';

export const alibabaModels = [
  {
    id: 'qwen-max',
    name: 'Qwen Max',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-max',
        inputPrice: 1.6 / 1e6,
        outputPrice: 6.4 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 32000,
        streaming: true,
        vision: true,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-max-latest',
    name: 'Qwen Max Latest',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-max-latest',
        inputPrice: 1.6 / 1e6,
        outputPrice: 6.4 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 32000,
        streaming: true,
        vision: true,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-plus',
    name: 'Qwen Plus',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-plus',
        inputPrice: 0.4 / 1e6,
        outputPrice: 1.2 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 32000,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-plus-latest',
    name: 'Qwen Plus Latest',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-plus-latest',
        inputPrice: 0.4 / 1e6,
        outputPrice: 1.2 / 1e6,
        requestPrice: 0,
        contextSize: 1000000,
        maxOutput: 32000,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-flash',
    name: 'Qwen Flash',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-flash',
        inputPrice: 0.05 / 1e6,
        outputPrice: 0.4 / 1e6,
        requestPrice: 0,
        contextSize: 1000000,
        maxOutput: 32000,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-omni-turbo',
    name: 'Qwen Omni Turbo',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-omni-turbo',
        inputPrice: 0.2 / 1e6,
        outputPrice: 0.8 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: true,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-turbo',
    name: 'Qwen Turbo',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-turbo',
        inputPrice: 0.05 / 1e6,
        outputPrice: 0.2 / 1e6,
        requestPrice: 0,
        contextSize: 1000000,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-coder-plus',
    name: 'Qwen3 Coder Plus',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen3-coder-plus',
        inputPrice: 6 / 1e6,
        outputPrice: 60 / 1e6,
        requestPrice: 0,
        contextSize: 1000000,
        maxOutput: 66000,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-qwq-32b',
    name: 'Qwen QwQ 32B',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/QwQ-32B',
        inputPrice: 0.15 / 1e6,
        outputPrice: 0.45 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-235b-a22b-instruct-2507',
    name: 'Qwen3 235B A22B Instruct 2507',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-235B-A22B-Instruct-2507',
        inputPrice: 0.2 / 1e6,
        outputPrice: 0.6 / 1e6,
        requestPrice: 0,
        contextSize: 262000,
        maxOutput: 8192,
        reasoning: false,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-235b-a22b-thinking-2507',
    name: 'Qwen3 235B A22B Thinking 2507',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-235B-A22B-Thinking-2507',
        inputPrice: 0.2 / 1e6,
        outputPrice: 0.6 / 1e6,
        requestPrice: 0,
        contextSize: 262000,
        maxOutput: 8192,
        reasoning: true,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-14b',
    name: 'Qwen3 14B',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-14B',
        inputPrice: 0.08 / 1e6,
        outputPrice: 0.24 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-32b',
    name: 'Qwen3 32B',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-32B',
        inputPrice: 0.1 / 1e6,
        outputPrice: 0.3 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-30b-a3b',
    name: 'Qwen3 30B A3B',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-30B-A3B',
        inputPrice: 0.1 / 1e6,
        outputPrice: 0.3 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen25-coder-7b',
    name: 'Qwen2.5 Coder 7B',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen2.5-Coder-7B-fast',
        inputPrice: 0.01 / 1e6,
        outputPrice: 0.03 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen25-32b-instruct',
    name: 'Qwen2.5 32B Instruct',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: new Date('2025-09-10'),
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen2.5-32B-Instruct',
        inputPrice: 0.06 / 1e6,
        outputPrice: 0.2 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen25-72b-instruct',
    name: 'Qwen2.5 72B Instruct',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen2.5-72B-Instruct',
        inputPrice: 0.13 / 1e6,
        outputPrice: 0.4 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen2-vl-72b-instruct',
    name: 'Qwen2 VL 72B Instruct',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: new Date('2025-09-10'),
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen2-VL-72B-Instruct',
        inputPrice: 0.13 / 1e6,
        outputPrice: 0.4 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: true,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen2-5-vl-72b-instruct',
    name: 'Qwen2.5 VL 72B Instruct',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen2.5-VL-72B-Instruct',
        inputPrice: 0.13 / 1e6,
        outputPrice: 0.4 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: 8192,
        streaming: true,
        vision: true,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-coder-480b-a35b-instruct',
    name: 'Qwen3 Coder 480B A35B Instruct',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
        inputPrice: 0.4 / 1e6,
        outputPrice: 1.8 / 1e6,
        requestPrice: 0,
        contextSize: 262000,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-coder-30b-a3b-instruct',
    name: 'Qwen3 Coder 30B A3B Instruct',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-Coder-30B-A3B-Instruct',
        inputPrice: 0.1 / 1e6,
        outputPrice: 0.3 / 1e6,
        requestPrice: 0,
        contextSize: 262000,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-30b-a3b-instruct-2507',
    name: 'Qwen3 30B A3B Instruct 2507',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-30B-A3B-Instruct-2507',
        inputPrice: 0.1 / 1e6,
        outputPrice: 0.3 / 1e6,
        requestPrice: 0,
        contextSize: 262000,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-30b-a3b-thinking-2507',
    name: 'Qwen3 30B A3B Thinking 2507',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'nebius',
        modelName: 'Qwen/Qwen3-30B-A3B-Thinking-2507',
        inputPrice: 0.1 / 1e6,
        outputPrice: 0.3 / 1e6,
        requestPrice: 0,
        contextSize: 262000,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
        reasoning: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-vl-max',
    name: 'Qwen VL Max',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-vl-max',
        inputPrice: 0.8 / 1e6,
        outputPrice: 3.2 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 32000,
        streaming: true,
        vision: true,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen-vl-plus',
    name: 'Qwen VL Plus',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen-vl-plus',
        inputPrice: 0.21 / 1e6,
        outputPrice: 0.64 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 32000,
        streaming: true,
        vision: true,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-next-80b-a3b-thinking',
    name: 'Qwen3 Next 80B A3B Thinking',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen3-next-80b-a3b-thinking',
        inputPrice: 0.5 / 1e6,
        outputPrice: 6 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 32768,
        reasoning: true,
        reasoningOutput: 'omit',
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-next-80b-a3b-instruct',
    name: 'Qwen3 Next 80B A3B Instruct',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen3-next-80b-a3b-instruct',
        inputPrice: 0.5 / 1e6,
        outputPrice: 2 / 1e6,
        requestPrice: 0,
        contextSize: 129024,
        maxOutput: 32768,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'qwen3-max',
    name: 'Qwen3 Max',
    family: 'alibaba',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'alibaba',
        modelName: 'qwen3-max-preview',
        inputPrice: 3 / 1e6,
        outputPrice: 15 / 1e6,
        cachedInputPrice: 0.6 / 1e6,
        requestPrice: 0,
        contextSize: 256000,
        maxOutput: 32800,
        reasoning: true,
        reasoningOutput: 'omit',
        streaming: true,
        vision: true,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
] as const satisfies ModelDefinition[];
