import type { ModelDefinition } from '.';

export const mistralModels = [
  {
    id: 'mistral-large-latest',
    name: 'Mistral Large Latest',
    family: 'mistral',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'mistral',
        modelName: 'mistral-large-latest',
        inputPrice: 0.000004,
        outputPrice: 0.000012,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: false,
  },
  {
    id: 'mixtral-8x7b-instruct-together',
    name: 'Mixtral 8x7B Instruct',
    family: 'mistral',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'together.ai',
        modelName: 'mistralai/mixtral-8x7b-instruct-v0.1',
        inputPrice: 0.06 / 1e6,
        outputPrice: 0.06 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'mistral-7b-instruct-together',
    name: 'Mistral 7B Instruct',
    family: 'mistral',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'together.ai',
        modelName: 'mistralai/mistral-7b-instruct-v0.1',
        inputPrice: 0.06 / 1e6,
        outputPrice: 0.06 / 1e6,
        requestPrice: 0,
        contextSize: 8192,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'pixtral-large-latest',
    name: 'Pixtral Large Latest',
    family: 'mistral',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'mistral',
        modelName: 'pixtral-large-latest',
        inputPrice: 0.000004,
        outputPrice: 0.000012,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        vision: true,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
] as const satisfies ModelDefinition[];
