import type { ModelDefinition } from '.';

export const moonshotModels = [
  {
    id: 'kimi-k2',
    name: 'Kimi K2',
    family: 'moonshot',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'groq',
        modelName: 'moonshotai/kimi-k2-instruct',
        inputPrice: 1.0 / 1e6,
        cachedInputPrice: 0.5 / 1e6,
        outputPrice: 3.0 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 16384,
        streaming: true,
        vision: false,
        tools: true,
      },
      {
        providerId: 'novita',
        modelName: 'moonshotai/kimi-k2-instruct',
        inputPrice: 0.57 / 1e6,
        outputPrice: 2.3 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 131072,
        streaming: true,
        vision: false,
        tools: true,
      },
      {
        providerId: 'moonshot',
        modelName: 'kimi-k2-0711-preview',
        inputPrice: 0.6 / 1e6,
        outputPrice: 2.5 / 1e6,
        cachedInputPrice: 0.15 / 1e6,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: 128000,
        streaming: true,
        vision: false,
        tools: true,
      },
      {
        providerId: 'cloudrift',
        modelName: 'moonshotai/Kimi-K2-Instruct',
        inputPrice: 0.3 / 1e6,
        outputPrice: 1.75 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 131072,
        streaming: true,
        vision: false,
        tools: true,
        test: 'skip',
      },
      {
        providerId: 'nebius',
        modelName: 'moonshotai/Kimi-K2-Instruct',
        inputPrice: 0.5 / 1e6,
        outputPrice: 2.4 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: 8192,
        streaming: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
] as const satisfies ModelDefinition[];
