import type { ModelDefinition } from '.';

export const routewayModels = [
  {
    id: 'deepseek-r1t2-chimera-free',
    name: 'DeepSeek R1T2 Chimera (Free)',
    family: 'deepseek',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'deepseek-r1t2-chimera:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 163840,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'glm-4.5-air-free',
    name: 'GLM-4.5 Air (Free)',
    family: 'glm',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'glm-4.5-air:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'kimi-k2-free',
    name: 'Kimi K2 (Free)',
    family: 'kimi',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'kimi-k2:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 32768,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'gpt-oss-20b-free',
    name: 'GPT OSS 20B (Free)',
    family: 'gpt-oss',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'gpt-oss-20b:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'gpt-4.1-free',
    name: 'GPT-4.1 (Free)',
    family: 'openai',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'gpt-4.1:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 1047576,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'llama-3.3-70b-instruct-free',
    name: 'Meta Llama 3.3 70B Instruct (Free)',
    family: 'meta',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'llama-3.3-70b-instruct:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 131072,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'llama-4-scout-free',
    name: 'Meta Llama 4 Scout (Free)',
    family: 'meta',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'llama-4-scout:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 1_000_000,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'llama-4-maverick-free',
    name: 'Meta Llama 4 Maverick (Free)',
    family: 'meta',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'llama-4-maverick:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 1_000_000,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'nemotron-nano-9b-v2',
    name: 'Nemotron Nano 9B V2',
    family: 'nvidia',
    free: true,
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'routeway',
        modelName: 'nemotron-nano-9b-v2:free',
        inputPrice: 0.0 / 1e6,
        outputPrice: 0.0 / 1e6,
        requestPrice: 0,
        contextSize: 128_000,
        maxOutput: undefined,
        streaming: true,
        vision: false,
        tools: false,
      },
    ],
    jsonOutput: true,
  },
] as const satisfies ModelDefinition[];
