import type { ModelDefinition } from '.';

export const zaiModels = [
  {
    id: 'glm-4.5',
    name: 'GLM-4.5',
    family: 'glm',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'zai',
        modelName: 'glm-4.5',
        inputPrice: 0.6 / 1e6,
        outputPrice: 2.2 / 1e6,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        reasoning: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'glm-4.5v',
    name: 'GLM-4.5V',
    family: 'glm',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'zai',
        modelName: 'glm-4.5v',
        inputPrice: 0.6 / 1e6,
        outputPrice: 1.8 / 1e6,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        reasoning: true,
        reasoningOutput: 'omit',
        vision: true,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'glm-4.5-air',
    name: 'GLM-4.5 Air',
    family: 'glm',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'zai',
        modelName: 'glm-4.5-air',
        inputPrice: 0.2 / 1e6,
        outputPrice: 1.1 / 1e6,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        reasoning: false,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'glm-4.5-x',
    name: 'GLM-4.5 X',
    family: 'glm',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'zai',
        modelName: 'glm-4.5-x',
        inputPrice: 2.2 / 1e6,
        outputPrice: 8.9 / 1e6,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        reasoning: true,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'glm-4.5-airx',
    name: 'GLM-4.5 AirX',
    family: 'glm',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'zai',
        modelName: 'glm-4.5-airx',
        inputPrice: 1.1 / 1e6,
        outputPrice: 4.5 / 1e6,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        reasoning: false,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'glm-4.5-flash',
    name: 'GLM-4.5 Flash',
    family: 'glm',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'zai',
        modelName: 'glm-4.5-flash',
        inputPrice: 0,
        outputPrice: 0,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        reasoning: false,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
  {
    id: 'glm-4-32b-0414-128k',
    name: 'GLM-4 32B (0414-128k)',
    family: 'glm',
    deprecatedAt: undefined,
    deactivatedAt: undefined,
    providers: [
      {
        providerId: 'zai',
        modelName: 'glm-4-32b-0414-128k',
        inputPrice: 0.1 / 1e6,
        outputPrice: 0.1 / 1e6,
        requestPrice: 0,
        contextSize: 128000,
        maxOutput: undefined,
        streaming: true,
        reasoning: false,
        vision: false,
        tools: true,
      },
    ],
    jsonOutput: true,
  },
] as const satisfies ModelDefinition[];
