name: V4 Release Tagging
on:
  push:
    branches: [ai-sdk-v4]
  workflow_dispatch: {}

jobs:
  tag-v4-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm typecheck
      - run: pnpm build
      - run: pnpm test
      - name: Create/Update v4 tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f v4
          git push origin v4 --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
